# Generated by Django 6.0.5 on 2026-05-27 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('gods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('helmet', 'Helmet'), ('boots', 'Boots'), ('accessory', 'Accessory')], max_length=20)),
                ('attack_bonus', models.IntegerField(default=0)),
                ('defense_bonus', models.IntegerField(default=0)),
                ('hp_bonus', models.IntegerField(default=0)),
                ('speed_bonus', models.IntegerField(default=0)),
                ('max_level', models.PositiveIntegerField(default=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipped_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_items', to='gods.playergod')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_instances', to='items.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.playerprofile')),
            ],
            options={
                'ordering': ['-level'],
            },
        ),
    ]
