# Generated by Django 6.0.5 on 2026-05-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='belongs_to_god',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='passive_atk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='passive_def',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='passive_desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='passive_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='passive_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='passive_spd',
            field=models.IntegerField(default=0),
        ),
    ]
