# Generated by Django 6.0.5 on 2026-05-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_belongs_to_god_item_passive_atk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('weapon', 'Arma'), ('armor', 'Armadura'), ('amulet', 'Amuleto')], max_length=20),
        ),
    ]
