# Generated by Django 6.0.5 on 2026-06-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='craft_cost',
            field=models.PositiveIntegerField(default=40),
        ),
    ]
