# Generated by Django 6.0.5 on 2026-05-30 19:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_missionresetlog_dailymission_in_pool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWheelSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('gems', 'Gemas'), ('gold', 'Oro'), ('nothing', 'Nada')], max_length=20)),
                ('reward_amount', models.PositiveIntegerField(default=0)),
                ('spun_date', models.DateField(default=datetime.date.today)),
                ('spun_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel_spins', to='core.playerprofile')),
            ],
            options={
                'verbose_name': 'Giro de Rueda',
                'verbose_name_plural': 'Giros de Rueda',
            },
        ),
        migrations.CreateModel(
            name='MemoryGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pairs_total', models.PositiveIntegerField(default=8)),
                ('moves', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('reward_claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('played_date', models.DateField(default=datetime.date.today)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_games', to='core.playerprofile')),
            ],
            options={
                'verbose_name': 'Juego de Memoria',
                'verbose_name_plural': 'Juegos de Memoria',
            },
        ),
    ]
