# Generated by Django 6.0.5 on 2026-05-31 17:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_missionresetlog_dailymission_in_pool_and_more'),
        ('minigames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_date', models.DateField(default=datetime.date.today)),
                ('board_state', models.JSONField(default=list)),
                ('player_hand', models.JSONField(default=list)),
                ('ai_hand', models.JSONField(default=list)),
                ('current_turn', models.CharField(default='player', max_length=10)),
                ('moves', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('won', models.BooleanField(null=True)),
                ('reward_claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_games', to='core.playerprofile')),
            ],
            options={
                'verbose_name': 'Duelo de Cartas',
                'verbose_name_plural': 'Duelos de Cartas',
            },
        ),
    ]
