services:
  - type: web
    name: immortal-gods
    env: python
    plan: free
    buildCommand: pip install uv && uv sync --frozen
    startCommand: bash entrypoint.sh
    envVars:
      - key: PYTHON_VERSION
        value: "3.13.0"
      - key: APP_DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: immortal-gods-db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: "4"

databases:
  - name: immortal-gods-db
    plan: free
    ipAllowList: []
