# Generated by Django 6.0.5 on 2026-05-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='gems',
            field=models.PositiveIntegerField(default=1350),
        ),
    ]
