# Generated by Django 6.0.5 on 2026-05-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_referralcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='rank_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
