# Generated by Django 6.0.5 on 2026-05-28 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_referralcode_used_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_type', models.CharField(choices=[('daily_login', 'Inicio de Sesión'), ('first_pull', 'Primera Invocación'), ('gacha_pulls', 'Invocaciones Múltiples'), ('win_battles', 'Victorias en Batalla'), ('level_up_god', 'Subir de Nivel'), ('ascend_god', 'Ascender Dios'), ('equip_item', 'Equipar Objeto'), ('win_campaign', 'Completar Campaña')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('target', models.PositiveIntegerField(default=1)),
                ('energy_reward', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('claimed', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dailymission')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='core.playerprofile')),
            ],
            options={
                'unique_together': {('player', 'mission')},
            },
        ),
    ]
