# Generated by Django 6.0.5 on 2026-05-29 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_daily_missions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailymission',
            old_name='energy_reward',
            new_name='gem_reward',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='max_energy',
        ),
        migrations.CreateModel(
            name='DailyLoginStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='core.playerprofile')),
            ],
        ),
    ]
