# Generated by Django 6.0.5 on 2026-05-29 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_energy_reward_dailymission_gem_reward_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('gems', models.PositiveIntegerField(default=0)),
                ('gold', models.PositiveIntegerField(default=0)),
                ('seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_notifications', to='core.playerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
