# Generated by Django 6.0.5 on 2026-05-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_giftnotification_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionResetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reset', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de reinicio de misiones',
                'verbose_name_plural': 'Registros de reinicio de misiones',
            },
        ),
        migrations.AddField(
            model_name='dailymission',
            name='in_pool',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dailymission',
            name='mission_type',
            field=models.CharField(choices=[('daily_login', 'Inicio de Sesión'), ('first_pull', 'Primera Invocación'), ('gacha_pulls', 'Invocaciones Múltiples'), ('win_battles', 'Victorias en Batalla'), ('level_up_god', 'Subir de Nivel'), ('ascend_god', 'Ascender Dios'), ('equip_item', 'Equipar Objeto'), ('win_campaign', 'Completar Campaña')], max_length=30),
        ),
    ]
