# Generated by Django 6.0.5 on 2026-05-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_missionresetlog_dailymission_in_pool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='card_deck',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
