# Generated by Django 6.0.5 on 2026-06-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_card_deck_to_playerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='triad_coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
