# Generated by Django 6.0.5 on 2026-06-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_playerprofile_triad_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='triad_coins',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='fragments',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
