# Generated by Django 6.0.5 on 2026-06-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_playerprofile_triad_coins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='fragments',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
