"""Management command to reseed god-specific items."""

from django.core.management.base import BaseCommand

from apps.items.models import Item, ItemType

ITEMS_DATA = [
    # Greek Gods - Zeus (3 items)
    {
        "name": "Espada del Rayo",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 50,
        "defense_bonus": 0,
        "hp_bonus": 0,
        "speed_bonus": 10,
        "belongs_to_god": "Zeus",
        "passive_name": "Invocador de Tormentas",
        "passive_desc": "Los rayos inflictan daño doble",
        "passive_atk": 30,
        "passive_def": 0,
        "passive_hp": 0,
        "passive_spd": 5,
    },
    {
        "name": "Egida de Zeus",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 10,
        "defense_bonus": 70,
        "hp_bonus": 250,
        "speed_bonus": 0,
        "belongs_to_god": "Zeus",
        "passive_name": "Escudo Divino",
        "passive_desc": "Crea una barrera impenetrable",
        "passive_atk": 0,
        "passive_def": 40,
        "passive_hp": 150,
        "passive_spd": 0,
    },
    {
        "name": "Corona de Zeus",
        "item_type": ItemType.AMULET,
        "attack_bonus": 20,
        "defense_bonus": 30,
        "hp_bonus": 100,
        "speed_bonus": 10,
        "belongs_to_god": "Zeus",
        "passive_name": "Autoridad del Rey",
        "passive_desc": "Ordena respeto de todos los dioses",
        "passive_atk": 15,
        "passive_def": 15,
        "passive_hp": 50,
        "passive_spd": 5,
    },
    # Greek Gods - Poseidon (3 items)
    {
        "name": "Tridente de Poseidón",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 60,
        "defense_bonus": 0,
        "hp_bonus": 0,
        "speed_bonus": 5,
        "belongs_to_god": "Poseidon",
        "passive_name": "Ira del Océano",
        "passive_desc": "Olas de marea destruyen enemigos",
        "passive_atk": 25,
        "passive_def": 0,
        "passive_hp": 100,
        "passive_spd": 0,
    },
    {
        "name": "Armadura del Rey del Mar",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 5,
        "defense_bonus": 55,
        "hp_bonus": 350,
        "speed_bonus": -5,
        "belongs_to_god": "Poseidon",
        "passive_name": "Profundidad Oceánica",
        "passive_desc": "La presión submarina fortalece la defensa",
        "passive_atk": 0,
        "passive_def": 30,
        "passive_hp": 200,
        "passive_spd": 0,
    },
    {
        "name": "Colmillo de Poseidón",
        "item_type": ItemType.AMULET,
        "attack_bonus": 15,
        "defense_bonus": 15,
        "hp_bonus": 150,
        "speed_bonus": 15,
        "belongs_to_god": "Poseidon",
        "passive_name": "Bendición de la Marea",
        "passive_desc": "Las corrientes guían todas las acciones",
        "passive_atk": 10,
        "passive_def": 10,
        "passive_hp": 100,
        "passive_spd": 10,
    },
    # Greek Gods - Hades (3 items)
    {
        "name": "Guadaña de Hades",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 70,
        "defense_bonus": 0,
        "hp_bonus": -50,
        "speed_bonus": 15,
        "belongs_to_god": "Hades",
        "passive_name": "Segador de Almas",
        "passive_desc": "Roba vida de enemigos caídos",
        "passive_atk": 40,
        "passive_def": 0,
        "passive_hp": 0,
        "passive_spd": 10,
    },
    {
        "name": "Manto del Inframundo",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 0,
        "defense_bonus": 50,
        "hp_bonus": 300,
        "speed_bonus": 0,
        "belongs_to_god": "Hades",
        "passive_name": "Abrazo de la Muerte",
        "passive_desc": "Las sombras dan protección",
        "passive_atk": 0,
        "passive_def": 35,
        "passive_hp": 150,
        "passive_spd": 0,
    },
    {
        "name": "Yelmo de la Oscuridad",
        "item_type": ItemType.AMULET,
        "attack_bonus": 20,
        "defense_bonus": 20,
        "hp_bonus": 100,
        "speed_bonus": 5,
        "belongs_to_god": "Hades",
        "passive_name": "Caminar entre Sombras",
        "passive_desc": "Se mueve sin ser visto por las sombras",
        "passive_atk": 15,
        "passive_def": 10,
        "passive_hp": 50,
        "passive_spd": 5,
    },
    # Greek Gods - Ares (3 items)
    {
        "name": "Espadas del Caos",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 65,
        "defense_bonus": 0,
        "hp_bonus": 0,
        "speed_bonus": 10,
        "belongs_to_god": "Ares",
        "passive_name": "Sed de Sangre",
        "passive_desc": "Gana fuerza del derramamiento de sangre",
        "passive_atk": 35,
        "passive_def": 0,
        "passive_hp": 0,
        "passive_spd": 5,
    },
    {
        "name": "Placas del Señor de la Guerra",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 15,
        "defense_bonus": 60,
        "hp_bonus": 200,
        "speed_bonus": -5,
        "belongs_to_god": "Ares",
        "passive_name": "Endurecido en Batalla",
        "passive_desc": "La victoria genera resiliencia",
        "passive_atk": 10,
        "passive_def": 30,
        "passive_hp": 100,
        "passive_spd": 0,
    },
    {
        "name": "Colgante de Cráneo",
        "item_type": ItemType.AMULET,
        "attack_bonus": 25,
        "defense_bonus": 10,
        "hp_bonus": 80,
        "speed_bonus": 10,
        "belongs_to_god": "Ares",
        "passive_name": "Guerrero",
        "passive_desc": "El dios de la guerra exige sangre",
        "passive_atk": 15,
        "passive_def": 5,
        "passive_hp": 50,
        "passive_spd": 5,
    },
    # Greek Gods - Athena (3 items)
    {
        "name": "Lanza de Atenea",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 55,
        "defense_bonus": 10,
        "hp_bonus": 50,
        "speed_bonus": 5,
        "belongs_to_god": "Athena",
        "passive_name": "Sabiduría Divina",
        "passive_desc": "Ventaja estratégica en batalla",
        "passive_atk": 25,
        "passive_def": 15,
        "passive_hp": 50,
        "passive_spd": 5,
    },
    {
        "name": "Escudo Égida",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 0,
        "defense_bonus": 65,
        "hp_bonus": 250,
        "speed_bonus": -5,
        "belongs_to_god": "Athena",
        "passive_name": "Protección Divina",
        "passive_desc": "El escudo refleja el 20% del daño",
        "passive_atk": 0,
        "passive_def": 35,
        "passive_hp": 150,
        "passive_spd": 0,
    },
    {
        "name": "Amuleto Ojo de lechuza",
        "item_type": ItemType.AMULET,
        "attack_bonus": 15,
        "defense_bonus": 25,
        "hp_bonus": 100,
        "speed_bonus": 10,
        "belongs_to_god": "Athena",
        "passive_name": "Ojo de Sabiduría",
        "passive_desc": "Ve a través de toda decepción",
        "passive_atk": 10,
        "passive_def": 15,
        "passive_hp": 50,
        "passive_spd": 10,
    },
    # Greek Gods - Apollo (3 items)
    {
        "name": "Arco de Apolo",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 55,
        "defense_bonus": 0,
        "hp_bonus": 0,
        "speed_bonus": 20,
        "belongs_to_god": "Apollo",
        "passive_name": "Perforador Solar",
        "passive_desc": "Las flechas queman a través de la armadura",
        "passive_atk": 20,
        "passive_def": 0,
        "passive_hp": 0,
        "passive_spd": 15,
    },
    {
        "name": "Armadura Solar",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 10,
        "defense_bonus": 50,
        "hp_bonus": 200,
        "speed_bonus": 5,
        "belongs_to_god": "Apollo",
        "passive_name": "Cuerpo Radiante",
        "passive_desc": "La luz proporciona protección",
        "passive_atk": 5,
        "passive_def": 30,
        "passive_hp": 100,
        "passive_spd": 5,
    },
    {
        "name": "Corona de Laurel",
        "item_type": ItemType.AMULET,
        "attack_bonus": 20,
        "defense_bonus": 15,
        "hp_bonus": 80,
        "speed_bonus": 15,
        "belongs_to_god": "Apollo",
        "passive_name": "Bendición del Sol",
        "passive_desc": "El sol guía todos los caminos",
        "passive_atk": 15,
        "passive_def": 10,
        "passive_hp": 50,
        "passive_spd": 10,
    },
    # Greek Gods - Artemis (3 items)
    {
        "name": "Arco Lunar",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 50,
        "defense_bonus": 0,
        "hp_bonus": 0,
        "speed_bonus": 25,
        "belongs_to_god": "Artemis",
        "passive_name": "Flecha de Luna",
        "passive_desc": "Flechas de plata nunca fallan",
        "passive_atk": 25,
        "passive_def": 0,
        "passive_hp": 0,
        "passive_spd": 15,
    },
    {
        "name": "Guardia del Cazador",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 5,
        "defense_bonus": 45,
        "hp_bonus": 180,
        "speed_bonus": 10,
        "belongs_to_god": "Artemis",
        "passive_name": "Instinto Bestial",
        "passive_desc": "La agilidad animal protege",
        "passive_atk": 0,
        "passive_def": 25,
        "passive_hp": 100,
        "passive_spd": 10,
    },
    {
        "name": "Colgante de Piedra Lunar",
        "item_type": ItemType.AMULET,
        "attack_bonus": 15,
        "defense_bonus": 15,
        "hp_bonus": 100,
        "speed_bonus": 20,
        "belongs_to_god": "Artemis",
        "passive_name": "Gracia Lunar",
        "passive_desc": "La luna empodera todas las acciones",
        "passive_atk": 10,
        "passive_def": 10,
        "passive_hp": 50,
        "passive_spd": 15,
    },
    # Greek Gods - Hermes (3 items)
    {
        "name": "Caduceo",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 45,
        "defense_bonus": 5,
        "hp_bonus": 0,
        "speed_bonus": 30,
        "belongs_to_god": "Hermes",
        "passive_name": "Golpe Rápido",
        "passive_desc": "Ataques rápidos como relámpagos",
        "passive_atk": 20,
        "passive_def": 0,
        "passive_hp": 0,
        "passive_spd": 20,
    },
    {
        "name": "Botas Aladas",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 5,
        "defense_bonus": 30,
        "hp_bonus": 100,
        "speed_bonus": 20,
        "belongs_to_god": "Hermes",
        "passive_name": "Caminante del Viento",
        "passive_desc": "Ligero como el viento",
        "passive_atk": 0,
        "passive_def": 20,
        "passive_hp": 50,
        "passive_spd": 15,
    },
    {
        "name": "Sandalias de Hermes",
        "item_type": ItemType.AMULET,
        "attack_bonus": 10,
        "defense_bonus": 10,
        "hp_bonus": 50,
        "speed_bonus": 40,
        "belongs_to_god": "Hermes",
        "passive_name": "Velocidad del Mensajero",
        "passive_desc": "Se mueve más rápido que el pensamiento",
        "passive_atk": 5,
        "passive_def": 5,
        "passive_hp": 0,
        "passive_spd": 30,
    },
    # Greek Gods - Hephaestus (3 items)
    {
        "name": "Martillo de Forja",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 60,
        "defense_bonus": 15,
        "hp_bonus": 50,
        "speed_bonus": -5,
        "belongs_to_god": "Hephaestus",
        "passive_name": "Golpe de Magma",
        "passive_desc": "El fuego mejora cada golpe",
        "passive_atk": 35,
        "passive_def": 10,
        "passive_hp": 0,
        "passive_spd": 0,
    },
    {
        "name": "Placas Divinas Forjadas",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 10,
        "defense_bonus": 70,
        "hp_bonus": 300,
        "speed_bonus": -10,
        "belongs_to_god": "Hephaestus",
        "passive_name": "Protección de Fuego",
        "passive_desc": "Forjado en llamas celestiales",
        "passive_atk": 0,
        "passive_def": 40,
        "passive_hp": 200,
        "passive_spd": 0,
    },
    {
        "name": "Botas de Hierro",
        "item_type": ItemType.AMULET,
        "attack_bonus": 5,
        "defense_bonus": 30,
        "hp_bonus": 100,
        "speed_bonus": -5,
        "belongs_to_god": "Hephaestus",
        "passive_name": "Caminante de la Forja",
        "passive_desc": "Inmune a lava y fuego",
        "passive_atk": 0,
        "passive_def": 20,
        "passive_hp": 50,
        "passive_spd": 0,
    },
    # Greek Gods - Demeter (3 items)
    {
        "name": "Guadaña de la Cosecha",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 45,
        "defense_bonus": 5,
        "hp_bonus": 50,
        "speed_bonus": 5,
        "belongs_to_god": "Demeter",
        "passive_name": "Ira de la Naturaleza",
        "passive_desc": "Las plantas enredan enemigos",
        "passive_atk": 20,
        "passive_def": 5,
        "passive_hp": 50,
        "passive_spd": 5,
    },
    {
        "name": "Manto de la Naturaleza",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 5,
        "defense_bonus": 45,
        "hp_bonus": 250,
        "speed_bonus": 5,
        "belongs_to_god": "Demeter",
        "passive_name": "Abrazo de la Tierra",
        "passive_desc": "La naturaleza proporciona refugio",
        "passive_atk": 0,
        "passive_def": 25,
        "passive_hp": 150,
        "passive_spd": 5,
    },
    {
        "name": "Semilla de Vida",
        "item_type": ItemType.AMULET,
        "attack_bonus": 10,
        "defense_bonus": 20,
        "hp_bonus": 200,
        "speed_bonus": 5,
        "belongs_to_god": "Demeter",
        "passive_name": "Regeneración",
        "passive_desc": "Energía vital sana constantemente",
        "passive_atk": 0,
        "passive_def": 10,
        "passive_hp": 150,
        "passive_spd": 0,
    },
    # Zodiac - Leo (3)
    {
        "name": "Garras de Leo",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 60,
        "defense_bonus": 5,
        "hp_bonus": 0,
        "speed_bonus": 15,
        "belongs_to_god": "Leo",
        "passive_name": "Golpe del Rey",
        "passive_desc": "El león ataca con autoridad",
        "passive_atk": 35,
        "passive_def": 0,
        "passive_hp": 0,
        "passive_spd": 10,
    },
    {
        "name": "Armadura de Melena Real",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 10,
        "defense_bonus": 55,
        "hp_bonus": 250,
        "speed_bonus": 0,
        "belongs_to_god": "Leo",
        "passive_name": "Fuerza del Orgullo",
        "passive_desc": "El rey de las bestias no puede ser derrotado",
        "passive_atk": 5,
        "passive_def": 30,
        "passive_hp": 150,
        "passive_spd": 0,
    },
    {
        "name": "Corona del Zodíaco",
        "item_type": ItemType.AMULET,
        "attack_bonus": 20,
        "defense_bonus": 20,
        "hp_bonus": 100,
        "speed_bonus": 20,
        "belongs_to_god": "Leo",
        "passive_name": "Alineación Estelar",
        "passive_desc": "Las constelaciones empoderan al portador",
        "passive_atk": 10,
        "passive_def": 10,
        "passive_hp": 50,
        "passive_spd": 10,
    },
    # Zodiac - Aries (3)
    {
        "name": "Espada de Cuernos de Carnero",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 55,
        "defense_bonus": 10,
        "hp_bonus": 0,
        "speed_bonus": 15,
        "belongs_to_god": "Aries",
        "passive_name": "Carga del Carnero",
        "passive_desc": "Nunca retroceder, siempre avanzar",
        "passive_atk": 30,
        "passive_def": 5,
        "passive_hp": 0,
        "passive_spd": 10,
    },
    {
        "name": "Abrigo de Lana",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 5,
        "defense_bonus": 50,
        "hp_bonus": 200,
        "speed_bonus": 5,
        "belongs_to_god": "Aries",
        "passive_name": "Lana Ignea",
        "passive_desc": "La calidez proporciona protección",
        "passive_atk": 0,
        "passive_def": 30,
        "passive_hp": 100,
        "passive_spd": 5,
    },
    {
        "name": "Vellocino de Oro",
        "item_type": ItemType.AMULET,
        "attack_bonus": 15,
        "defense_bonus": 25,
        "hp_bonus": 150,
        "speed_bonus": 10,
        "belongs_to_god": "Aries",
        "passive_name": "Escudo Mítico",
        "passive_desc": "Protección legendaria contra todo daño",
        "passive_atk": 10,
        "passive_def": 15,
        "passive_hp": 100,
        "passive_spd": 5,
    },
    # Zodiac - Taurus (3)
    {
        "name": "Cuernos del Toro",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 50,
        "defense_bonus": 15,
        "hp_bonus": 100,
        "speed_bonus": -5,
        "belongs_to_god": "Taurus",
        "passive_name": "Fuerza Inmóvil",
        "passive_desc": "Fuerte como la tierra misma",
        "passive_atk": 25,
        "passive_def": 15,
        "passive_hp": 100,
        "passive_spd": 0,
    },
    {
        "name": "Piel de Piedra",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 0,
        "defense_bonus": 70,
        "hp_bonus": 350,
        "speed_bonus": -10,
        "belongs_to_god": "Taurus",
        "passive_name": "Defensa de la Montaña",
        "passive_desc": "Inmóvil e irrompible",
        "passive_atk": 0,
        "passive_def": 45,
        "passive_hp": 200,
        "passive_spd": 0,
    },
    {
        "name": "Gema de la Tierra",
        "item_type": ItemType.AMULET,
        "attack_bonus": 10,
        "defense_bonus": 30,
        "hp_bonus": 200,
        "speed_bonus": 0,
        "belongs_to_god": "Taurus",
        "passive_name": "Bendición de la Tierra",
        "passive_desc": "La tierra da fuerza",
        "passive_atk": 5,
        "passive_def": 20,
        "passive_hp": 150,
        "passive_spd": 0,
    },
    # Zodiac - Scorpio (3)
    {
        "name": "Aguijón Venenoso",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 65,
        "defense_bonus": 0,
        "hp_bonus": -30,
        "speed_bonus": 10,
        "belongs_to_god": "Scorpio",
        "passive_name": "Veneno Mortal",
        "passive_desc": "El veneno debilita a todos los enemigos",
        "passive_atk": 40,
        "passive_def": 0,
        "passive_hp": 0,
        "passive_spd": 5,
    },
    {
        "name": "Caparazón del Escorpión",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 5,
        "defense_bonus": 55,
        "hp_bonus": 200,
        "speed_bonus": 0,
        "belongs_to_god": "Scorpio",
        "passive_name": "Escudo Venenoso",
        "passive_desc": "El caparazón venenoso protege",
        "passive_atk": 5,
        "passive_def": 35,
        "passive_hp": 100,
        "passive_spd": 0,
    },
    {
        "name": "Colgante del Aguijón",
        "item_type": ItemType.AMULET,
        "attack_bonus": 20,
        "defense_bonus": 15,
        "hp_bonus": 80,
        "speed_bonus": 15,
        "belongs_to_god": "Scorpio",
        "passive_name": "Maestro de la Emboscada",
        "passive_desc": "Ataca cuando menos se espera",
        "passive_atk": 15,
        "passive_def": 10,
        "passive_hp": 50,
        "passive_spd": 10,
    },
    # Zodiac - Sagittarius (3)
    {
        "name": "Arco Celestial",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 60,
        "defense_bonus": 0,
        "hp_bonus": 0,
        "speed_bonus": 20,
        "belongs_to_god": "Sagittarius",
        "passive_name": "Flecha Estelar",
        "passive_desc": "Las flechas caen como meteoros",
        "passive_atk": 35,
        "passive_def": 0,
        "passive_hp": 0,
        "passive_spd": 15,
    },
    {
        "name": " Pezuñas de Centauro",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 10,
        "defense_bonus": 45,
        "hp_bonus": 180,
        "speed_bonus": 10,
        "belongs_to_god": "Sagittarius",
        "passive_name": "Movimiento Rápido",
        "passive_desc": "Galopa por el campo de batalla",
        "passive_atk": 5,
        "passive_def": 25,
        "passive_hp": 100,
        "passive_spd": 10,
    },
    {
        "name": "Amuleto de Flecha",
        "item_type": ItemType.AMULET,
        "attack_bonus": 20,
        "defense_bonus": 10,
        "hp_bonus": 80,
        "speed_bonus": 20,
        "belongs_to_god": "Sagittarius",
        "passive_name": "Disparo Perfecto",
        "passive_desc": "Nunca falla el objetivo",
        "passive_atk": 15,
        "passive_def": 5,
        "passive_hp": 50,
        "passive_spd": 15,
    },
    # Zodiac - Aquarius (3)
    {
        "name": "Vasija del Portador de Agua",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 50,
        "defense_bonus": 10,
        "hp_bonus": 50,
        "speed_bonus": 15,
        "belongs_to_god": "Aquarius",
        "passive_name": "Ola de Marea",
        "passive_desc": "El agua aplasta todos los obstáculos",
        "passive_atk": 25,
        "passive_def": 5,
        "passive_hp": 50,
        "passive_spd": 10,
    },
    {
        "name": "Armadura Cósmica",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 10,
        "defense_bonus": 50,
        "hp_bonus": 250,
        "speed_bonus": 5,
        "belongs_to_god": "Aquarius",
        "passive_name": "Protección Estelar",
        "passive_desc": "El agua cósmica protege el cuerpo",
        "passive_atk": 5,
        "passive_def": 30,
        "passive_hp": 150,
        "passive_spd": 5,
    },
    {
        "name": "Anillo de Acuario",
        "item_type": ItemType.AMULET,
        "attack_bonus": 15,
        "defense_bonus": 20,
        "hp_bonus": 150,
        "speed_bonus": 15,
        "belongs_to_god": "Aquarius",
        "passive_name": "Espíritu del Agua",
        "passive_desc": "Fluye como el agua en batalla",
        "passive_atk": 10,
        "passive_def": 10,
        "passive_hp": 100,
        "passive_spd": 10,
    },
    # Zodiac - Pisces (3)
    {
        "name": "Cetro de Pez",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 45,
        "defense_bonus": 15,
        "hp_bonus": 80,
        "speed_bonus": 10,
        "belongs_to_god": "Pisces",
        "passive_name": "Llamada del Océano",
        "passive_desc": "El mar responde a cada llamada",
        "passive_atk": 20,
        "passive_def": 10,
        "passive_hp": 80,
        "passive_spd": 5,
    },
    {
        "name": "Malla de Escamas de Pez",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 5,
        "defense_bonus": 50,
        "hp_bonus": 280,
        "speed_bonus": 0,
        "belongs_to_god": "Pisces",
        "passive_name": "Escudo del Mar Profundo",
        "passive_desc": "Las profundidades protegen a los suyos",
        "passive_atk": 0,
        "passive_def": 30,
        "passive_hp": 180,
        "passive_spd": 0,
    },
    {
        "name": "Colgante de Pez Lunar",
        "item_type": ItemType.AMULET,
        "attack_bonus": 15,
        "defense_bonus": 20,
        "hp_bonus": 150,
        "speed_bonus": 10,
        "belongs_to_god": "Pisces",
        "passive_name": "Caminante de Sueños",
        "passive_desc": "Los sueños se vuelven realidad",
        "passive_atk": 10,
        "passive_def": 10,
        "passive_hp": 100,
        "passive_spd": 5,
    },
    # Zodiac - Gemini (3)
    {
        "name": "Espadas Gemelas",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 55,
        "defense_bonus": 5,
        "hp_bonus": 0,
        "speed_bonus": 20,
        "belongs_to_god": "Gemini",
        "passive_name": "Golpe Gemelo",
        "passive_desc": "Dos golpes por el precio de uno",
        "passive_atk": 30,
        "passive_def": 0,
        "passive_hp": 0,
        "passive_spd": 15,
    },
    {
        "name": "Escudo Dual",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 10,
        "defense_bonus": 55,
        "hp_bonus": 200,
        "speed_bonus": 5,
        "belongs_to_god": "Gemini",
        "passive_name": "Imagen Espejo",
        "passive_desc": "Crea copias para confundir enemigos",
        "passive_atk": 5,
        "passive_def": 35,
        "passive_hp": 100,
        "passive_spd": 5,
    },
    {
        "name": "Amuleto Estrella Gemela",
        "item_type": ItemType.AMULET,
        "attack_bonus": 20,
        "defense_bonus": 15,
        "hp_bonus": 100,
        "speed_bonus": 20,
        "belongs_to_god": "Gemini",
        "passive_name": "Poder Estelar",
        "passive_desc": "Las estrellas se alinean para la victoria",
        "passive_atk": 15,
        "passive_def": 10,
        "passive_hp": 50,
        "passive_spd": 15,
    },
    # Zodiac - Virgo (3)
    {
        "name": "Hoz de Trigo",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 45,
        "defense_bonus": 10,
        "hp_bonus": 50,
        "speed_bonus": 10,
        "belongs_to_god": "Virgo",
        "passive_name": "Bendición de la Cosecha",
        "passive_desc": "La abundancia empodera todas las acciones",
        "passive_atk": 20,
        "passive_def": 5,
        "passive_hp": 50,
        "passive_spd": 5,
    },
    {
        "name": "Túnicas Blancas Puras",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 5,
        "defense_bonus": 50,
        "hp_bonus": 220,
        "speed_bonus": 5,
        "belongs_to_god": "Virgo",
        "passive_name": "Purificación",
        "passive_desc": "La pureza escudo del daño",
        "passive_atk": 0,
        "passive_def": 30,
        "passive_hp": 120,
        "passive_spd": 5,
    },
    {
        "name": "Amuleto de la Cosecha",
        "item_type": ItemType.AMULET,
        "attack_bonus": 15,
        "defense_bonus": 20,
        "hp_bonus": 150,
        "speed_bonus": 10,
        "belongs_to_god": "Virgo",
        "passive_name": "Don de la Madre Tierra",
        "passive_desc": "La bounté de la naturaleza es inagotable",
        "passive_atk": 10,
        "passive_def": 10,
        "passive_hp": 100,
        "passive_spd": 5,
    },
    # Zodiac - Libra (3)
    {
        "name": "Espada de la Balanza",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 50,
        "defense_bonus": 10,
        "hp_bonus": 50,
        "speed_bonus": 10,
        "belongs_to_god": "Libra",
        "passive_name": "Golpe de Equilibrio",
        "passive_desc": "Equilibrio perfecto en cada ataque",
        "passive_atk": 25,
        "passive_def": 5,
        "passive_hp": 50,
        "passive_spd": 10,
    },
    {
        "name": "Escudo de la Justicia",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 10,
        "defense_bonus": 50,
        "hp_bonus": 200,
        "speed_bonus": 5,
        "belongs_to_god": "Libra",
        "passive_name": "Guardia de la Justicia",
        "passive_desc": "La justicia protege a los justos",
        "passive_atk": 5,
        "passive_def": 30,
        "passive_hp": 100,
        "passive_spd": 5,
    },
    {
        "name": "Colgante de la Balanza",
        "item_type": ItemType.AMULET,
        "attack_bonus": 15,
        "defense_bonus": 20,
        "hp_bonus": 120,
        "speed_bonus": 15,
        "belongs_to_god": "Libra",
        "passive_name": "Igualdad",
        "passive_desc": "Todas las fuerzas están en armonía",
        "passive_atk": 10,
        "passive_def": 10,
        "passive_hp": 70,
        "passive_spd": 10,
    },
    # Zodiac - Cancer (3)
    {
        "name": "Pinzas de Cangrejo",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 45,
        "defense_bonus": 15,
        "hp_bonus": 100,
        "speed_bonus": 0,
        "belongs_to_god": "Cancer",
        "passive_name": "Rotura de Caparazón",
        "passive_desc": "El caparazón duro aplasta todas las defensas",
        "passive_atk": 20,
        "passive_def": 10,
        "passive_hp": 100,
        "passive_spd": 0,
    },
    {
        "name": "Armadura de Caparazón",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 0,
        "defense_bonus": 60,
        "hp_bonus": 300,
        "speed_bonus": -5,
        "belongs_to_god": "Cancer",
        "passive_name": "Cambiador de Mareas",
        "passive_desc": "La luna controla las mareas",
        "passive_atk": 0,
        "passive_def": 40,
        "passive_hp": 200,
        "passive_spd": 0,
    },
    {
        "name": "Colgante de Caparazón Lunar",
        "item_type": ItemType.AMULET,
        "attack_bonus": 10,
        "defense_bonus": 25,
        "hp_bonus": 180,
        "speed_bonus": 5,
        "belongs_to_god": "Cancer",
        "passive_name": "Protección Lunar",
        "passive_desc": "La luna proporciona fuerza",
        "passive_atk": 5,
        "passive_def": 15,
        "passive_hp": 120,
        "passive_spd": 5,
    },
    # Zodiac - Capricorn (3)
    {
        "name": "Lanza de Cuerno de Cabra",
        "item_type": ItemType.WEAPON,
        "attack_bonus": 50,
        "defense_bonus": 15,
        "hp_bonus": 50,
        "speed_bonus": 5,
        "belongs_to_god": "Capricorn",
        "passive_name": "Escalador de Montañas",
        "passive_desc": "No para hasta la cima",
        "passive_atk": 25,
        "passive_def": 10,
        "passive_hp": 50,
        "passive_spd": 5,
    },
    {
        "name": "Capa de Cabra de Mar",
        "item_type": ItemType.ARMOR,
        "attack_bonus": 10,
        "defense_bonus": 55,
        "hp_bonus": 280,
        "speed_bonus": 0,
        "belongs_to_god": "Capricorn",
        "passive_name": "Adaptabilidad",
        "passive_desc": "Se adapta a cualquier entorno",
        "passive_atk": 5,
        "passive_def": 35,
        "passive_hp": 180,
        "passive_spd": 0,
    },
    {
        "name": "Amuleto de la Cima",
        "item_type": ItemType.AMULET,
        "attack_bonus": 15,
        "defense_bonus": 25,
        "hp_bonus": 150,
        "speed_bonus": 10,
        "belongs_to_god": "Capricorn",
        "passive_name": "Ambición",
        "passive_desc": "Alcanza alturas desconocidas",
        "passive_atk": 10,
        "passive_def": 15,
        "passive_hp": 100,
        "passive_spd": 5,
    },
]


class Command(BaseCommand):
    """Reseed god-specific items."""

    help = "Delete and recreate all god-specific items"

    def handle(self, *args, **options):
        deleted, _ = (
            Item.objects.filter(belongs_to_god__isnull=False)
            .exclude(belongs_to_god="")
            .delete()
        )
        self.stdout.write(f"Deleted {deleted} god-specific items")

        created = 0
        for data in ITEMS_DATA:
            Item.objects.create(**data)
            created += 1

        self.stdout.write(self.style.SUCCESS(f"Created {created} god-specific items"))
