# Generated by Django 6.0.5 on 2026-05-27 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='God',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('pantheon', models.CharField(choices=[('greek', 'Greek'), ('zodiac', 'Zodiac'), ('chinese', 'Chinese'), ('egyptian', 'Egyptian'), ('nordic', 'Nordic')], max_length=20)),
                ('role', models.CharField(choices=[('assassin', 'Assassin'), ('tank', 'Tank'), ('support', 'Support'), ('mage', 'Mage'), ('archer', 'Archer')], max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary'), ('mythic', 'Mythic')], max_length=20)),
                ('base_attack', models.PositiveIntegerField(default=100)),
                ('base_defense', models.PositiveIntegerField(default=100)),
                ('base_hp', models.PositiveIntegerField(default=1000)),
                ('base_speed', models.PositiveIntegerField(default=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gods/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rarity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerGod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('god', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_owners', to='gods.god')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gods', to='core.playerprofile')),
            ],
            options={
                'ordering': ['-level', 'god__name'],
                'unique_together': {('player', 'god')},
            },
        ),
    ]
