# Generated by Django 6.0.5 on 2026-05-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergod',
            name='essence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playergod',
            name='quality_tier',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
