# Generated by Django 6.0.5 on 2026-05-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gods', '0002_add_essence_and_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='god',
            name='pantheon',
            field=models.CharField(choices=[('greek', 'Greek'), ('aztec', 'Aztec'), ('chinese', 'Chinese'), ('egyptian', 'Egyptian'), ('nordic', 'Nordic')], max_length=20),
        ),
    ]
