# Generated by Django 6.0.5 on 2026-05-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gods', '0004_add_synergy_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergod',
            name='card_bonus',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
