# Generated by Django 6.0.5 on 2026-05-29 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_missionresetlog_dailymission_in_pool_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PvPBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_snapshot', models.JSONField(default=dict)),
                ('defender_snapshot', models.JSONField(default=dict)),
                ('attacker_rating_change', models.IntegerField(default=0)),
                ('defender_rating_change', models.IntegerField(default=0)),
                ('battle_log', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvp_attacks', to='core.playerprofile')),
                ('attacker_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvp_defenses', to='core.playerprofile')),
                ('defender_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pvp_wins', to='core.playerprofile')),
            ],
            options={
                'verbose_name': 'Batalla PvP',
                'verbose_name_plural': 'Batallas PvP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PvPProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1000)),
                ('highest_rating', models.IntegerField(default=1000)),
                ('battles_played', models.PositiveIntegerField(default=0)),
                ('battles_won', models.PositiveIntegerField(default=0)),
                ('rank', models.CharField(choices=[('bronze', 'Bronce'), ('silver', 'Plata'), ('gold', 'Oro'), ('platinum', 'Platino'), ('diamond', 'Diamante'), ('mythic', 'Mítico')], default='bronze', max_length=20)),
                ('in_queue', models.BooleanField(default=False)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pvp', to='core.playerprofile')),
            ],
            options={
                'verbose_name': 'Perfil PvP',
                'verbose_name_plural': 'Perfiles PvP',
            },
        ),
    ]
