# Generated by Django 6.0.5 on 2026-05-29 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_missionresetlog_dailymission_in_pool_and_more'),
        ('pvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvpbattle',
            name='bot_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pvpbattle',
            name='bot_rating',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='pvpbattle',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pvpbattle',
            name='defender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pvp_defenses', to='core.playerprofile'),
        ),
    ]
