# Generated by Django 6.0.5 on 2026-05-30 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_missionresetlog_dailymission_in_pool_and_more'),
        ('pvp', '0002_pvpbattle_bot_name_pvpbattle_bot_rating_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pvpbattle',
            name='bot_name',
        ),
        migrations.RemoveField(
            model_name='pvpbattle',
            name='bot_rating',
        ),
        migrations.RemoveField(
            model_name='pvpbattle',
            name='is_bot',
        ),
        migrations.RemoveField(
            model_name='pvpprofile',
            name='in_queue',
        ),
        migrations.RemoveField(
            model_name='pvpprofile',
            name='queued_at',
        ),
        migrations.AddField(
            model_name='pvpprofile',
            name='defense_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='pvpbattle',
            name='defender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvp_defenses', to='core.playerprofile'),
        ),
    ]
