# Generated by Django 6.0.5 on 2026-05-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvp', '0003_async_pvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvpprofile',
            name='daily_attacks_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvpprofile',
            name='daily_attacks_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
