# Generated by Django 6.0.5 on 2026-05-27 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('gods', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.CharField(choices=[('standard', 'Standard'), ('greek', 'Greek Pantheon'), ('zodiac', 'Zodiac Pantheon'), ('chinese', 'Chinese Pantheon'), ('egyptian', 'Egyptian Pantheon'), ('nordic', 'Nordic Pantheon')], max_length=20)),
                ('pull_type', models.CharField(choices=[('single', 'Single Pull'), ('multi', 'Multi Pull (x10)')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('god', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gods.god')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulls', to='core.playerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
