# Generated by Django 6.0.5 on 2026-05-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullhistory',
            name='banner',
            field=models.CharField(choices=[('standard', 'Standard')], max_length=20),
        ),
    ]
