# Generated by Django 6.0.5 on 2026-05-27 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard'), ('hell', 'Hell')], max_length=10)),
                ('order', models.PositiveIntegerField(unique=True)),
                ('energy_cost', models.PositiveIntegerField(default=10)),
                ('gold_reward', models.PositiveIntegerField(default=200)),
                ('gems_reward', models.PositiveIntegerField(default=10)),
                ('exp_reward', models.PositiveIntegerField(default=50)),
                ('required_power', models.PositiveIntegerField(default=500)),
                ('is_boss_level', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CampaignBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won', models.BooleanField()),
                ('turns', models.PositiveIntegerField(default=1)),
                ('gold_earned', models.PositiveIntegerField(default=0)),
                ('gems_earned', models.PositiveIntegerField(default=0)),
                ('exp_earned', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='core.playerprofile')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles', to='teams.team')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='campaign.campaignlevel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
