# Generated by Django 6.0.5 on 2026-05-27 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
        ('core', '0004_playerprofile_rank_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactionLadder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pantheon', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#4a9eff', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FactionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_floor', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='campaign.factionladder')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_progress', to='core.playerprofile')),
            ],
            options={
                'ordering': ['-highest_floor'],
                'unique_together': {('player', 'ladder')},
            },
        ),
        migrations.CreateModel(
            name='FactionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('required_power', models.PositiveIntegerField(default=500)),
                ('is_boss', models.BooleanField(default=False)),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='campaign.factionladder')),
            ],
            options={
                'ordering': ['ladder', 'floor'],
                'unique_together': {('ladder', 'floor')},
            },
        ),
    ]
