# Generated by Django 6.0.5 on 2026-05-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_factionladder_factionprogress_factionstage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignlevel',
            name='energy_cost',
        ),
    ]
