# Generated by Django 6.0.5 on 2026-05-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_remove_campaignlevel_energy_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlevel',
            name='enemy_team_data',
            field=models.JSONField(blank=True, default=list, help_text='List of enemy god configurations for this level'),
        ),
    ]
