# Generated by Django 6.0.5 on 2026-05-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_campaignlevel_enemy_team_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignbattle',
            name='log_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
